name: Travelogician
favicon: null
layout_spectrum: 0.61955
typography_spectrum: 0.13011
title: Figuring it all out
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afb8c6'
    - '#dde4ee'
    - '#20221d'
    - '#8393ac'
    - '#5a5531'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
